string gametitle = "*****THE LANDS BETWEEN*****";
string heroname = "Vyke the Roundtable Knight";
string heroclass = "Knight";
string weapon = "Vyke's War Spear";
string mission = "Stand before the Elden Ring and become the Elden Lord";
string storyintro = "The fallen leaves tell a story. The great Elden Ring was shattered. In our home, across the fog, the Lands Between Now, Queen Marika the Eternal is nowhere to be found, and in the Night of the Black Knives, Godwyn the Golden was the first to perish. Soon, Marika's offspring, demigods all, claimed the shards of the Elden Ring. The mad taint of their newfound strength triggered the Shattering. A war from which no lord arose. A war leading to abandonment by the Greater Will. Arise now, ye Tarnished. Ye dead, who yet live. The call of long-lost grace speaks to us all. Hoarah Loux, chieftan of the badlands. The ever-brilliant Goldmask. Fia, the Deathbed Companion. The loathsome Dung Eater. And Sir Gideon Ofnir, the All-knowing. And one other. Whom grace would again bless. A Tarnished of no renown. Cross the fog, to the Lands Between. To stand before the Elden Ring. And become the Elden Lord.";

Console.WriteLine("***********************************");
Console.WriteLine(gametitle);
Console.WriteLine("***********************************");
Console.WriteLine("");
Console.WriteLine("LOADING PLAYER PROFILE...");
Console.WriteLine("");
Console.WriteLine("HERO NAME: " + heroname);
Console.WriteLine("CLASS:" + heroclass);
Console.Writeline("WEAPON:" + weapon);
Console.WriteLine("MISSION:" + mission);
Console.WriteLine("");
Console.Writeline("STORY:");
Console.WriteLine(storyintro);
Console.Writeline("");
Console.writeline("***********************************");
Console.WriteLine("PRESS ANY BOTTON TO START");